Add sortable checkboxes for description source
ShokoAnime/Shokofin pull request #42
Opened 2023-11-28 23:38 UTC by fearnlj01

Hopefully this should be a somewhat passable implementation of converting the description source option to being driven by orderable checkboxes (at least, in the opening state of the PR, just for further development purposes).

The changes to the plugin settings include one new setting, and one re-purposed setting.
- `DescriptionSourceOrder` has been added as an array and allows the user selected order for the description sources to persist.
- `DescriptionSource` has been repurposed into an array, containing any of the checked options

At a minimum, with these (client side only) changes implemented, the plugin settings render as expected, and there should hopefully be no further need for any significant new client side changes (for the sortable checkboxes at least).

By no means is this even slightly near ready to be merged, but all things must start somewhere (not helped by my own lack of ability).

2024-04-12 00:17 UTC, fearnlj01 commented
Rebased the changes on top of master now. I've not double checked that things work as expected, just manually resolved merge conflicts so don't put any faith in this!

I'll review further in the morning and advise if I think I'll be able to handle the C# side of things.

2024-04-12 09:40 UTC, fearnlj01 commented
Further update just to note that it's not fully working as expected... But it is saving as expected.

Will return to this later today!

2024-04-12 10:14 UTC, fearnlj01 commented
I think this is hunky dory now... Will request a review once I test the setting migration (that I completely forgot I had tried to setup...)

2024-04-12 19:12 UTC, fearnlj01 commented
If we don't care for setting migration at all... The PR can be simplified, and the new configuration entry, `DescriptionSourceList` can return back to being `DescriptionSource`.

2024-04-13 08:11 UTC, revam commented
Personally I don't care since we don't have a framework in place (yet) to update the xml before it's parsed. And 4.0.0 will be a breaking change, so putting a note in that the users need to go through their plugin settings is probably mandatory at this point, since none of the other new settings have a migration (yet at least).

2024-04-13 10:34 UTC, fearnlj01 commented
Marking back as a draft as the below shouldn't be happening when the settings page is rendered...
![image](https://github.com/ShokoAnime/Shokofin/assets/13705865/22532af5-6055-42d7-bbbb-9a2e2a265bc8)

Once fixed will mark as ready for review again.

2024-04-13 13:01 UTC, fearnlj01 commented
Okay, I've tested it a fair bit now and I'm happy that it works as expected.

The capability for Migrations is now removed, probably best not to introduce "hacks" to migrate... At the very least, instead of continuing with `DescriptionSource`, this PR now uses `DescriptionSourceList`, so there should be no issues with invalid configurations, and it will simply return to default settings for existing users.

2024-04-13 21:07 UTC, revam requested changes
Can you revert the changes for `JoinText` since it's used for _both_ the titles _and_ the descriptions, and instead add a `?? string.Empty` to the return value when used for the descriptions?

Also, can you collapse the get description for season/episode methods again, returning them to an arrow function format?

2024-04-13 21:25 UTC, revam approved these changes
:+1:

2024-04-13 21:26 UTC, merged